name: New Issue Listener
on:
  issues:
    types:
      - opened

jobs:
  listen-to-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Echo Issue Number
        run: |
          echo "New issue opened! Issue number: ${{ github.event.issue.number }}"

