name: 'Run SSA Bot'
on:
  workflow_dispatch:
  
jobs:
  launch-ssa-bot:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github

      - name: install CLI dependencies
        run: |
          git clone --branch feature/use-cli https://github.com/keyko-io/filecoin-auto-datacap-allocation-bot.git ssa-bot-repo
          cd ssa-bot-repo
          npm install
          npm run build
          npm link

      - name: Execute CLI command and display help
        run: ssa-bot -h
        env:
          GITHUB_LDN_REPO_OWNER: ${{ secrets.SSA_GITHUB_LDN_REPO_OWNER }}
          GITHUB_LDN_REPO: ${{ secrets.SSA_GITHUB_LDN_REPO }}
          GITHUB_NOTARY_REPO: ${{ secrets.SSA_GITHUB_NOTARY_REPO }}
          NODE_URL: ${{ secrets.SSA_NODE_URL }}
          LOTUS_NODE_TOKEN: ${{ secrets.SSA_LOTUS_NODE_TOKEN }}
          NETWORK_TYPE: ${{ secrets.SSA_NETWORK_TYPE }}
          API_KEY: ${{ secrets.SSA_API_KEY }}
          APP_ID: ${{ secrets.SSA_APP_ID }}
          CLIENT_ID: ${{ secrets.SSA_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SSA_CLIENT_SECRET }}
          GIT_PRIVATE_KEY: ${{ secrets.SSA_GIT_PRIVATE_KEY }}
          INSTALLATION_ID: ${{ secrets.SSA_INSTALLATION_ID }}
          GIT_BEGIN_PK: ${{ secrets.SSA_GIT_BEGIN_PK }}
          GIT_END_PK: ${{ secrets.SSA_GIT_END_PK }}
          V3_MULTISIG_ADDRESS: ${{ secrets.SSA_V3_MULTISIG_ADDRESS }}
          V3_MULTISIG_ISSUE_NUMBER: ${{ secrets.SSA_V3_MULTISIG_ISSUE_NUMBER }}
          HEALTH_CEHECK_ISSUE: ${{ secrets.SSA_HEALTH_CEHECK_ISSUE }}
